version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    restart: unless-stopped
