version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend  # pour développement avec reload
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --reload

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
